apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: forgejo
spec:
  destination:
    name: in-cluster
    namespace: forgejo
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
  source:
    repoURL: code.forgejo.org/forgejo-helm
    chart: forgejo
    targetRevision: 13.0.0
    helm:
      valuesObject:
        strategy:
          type: Recreate
        gitea:
          config:
            database:
              DB_TYPE: sqlite3
            session:
              PROVIDER: memory
            cache:
              ADAPTER: memory
            queue:
              TYPE: level
            server:
              LANDING_PAGE: explore
              ROOT_URL: https://code.lajas.tech
              OFFLINE_MODE: true
            repository:
              DISABLED_REPO_UNITS: repo.wiki,repo.projects,repo.packages
              DISABLE_STARS: true
              DEFAULT_BRANCH: master
            oauth2_client:
              ENABLE_AUTO_REGISTRATION: true
              OPENID_CONNECT_SCOPES: "email profile"
              USERNAME: username
            service:
              ENABLE_INTERNAL_SIGNIN: false
              ALLOW_ONLY_EXTERNAL_REGISTRATION: true
            "service.explore":
              DISABLE_USERS_PAGE: true
            actions:
              ENABLED: false
            webhook:
              ALLOWED_HOST_LIST: "private"
            other:
              SHOW_FOOTER_VERSION: false
              SHOW_FOOTER_TEMPLATE_LOAD_TIME: false
              SHOW_FOOTER_POWERED_BY: false
        oauth:
          - name: SSO
            provider: 'openidConnect'
            autoDiscoverUrl: https://dex.cloudlab.lajas.tech/.well-known/openid-configuration
            existingSecret: forgejo-oauth
        admin:
          email: admin@cloudlab.lajas.tech
          existingSecret: forgejo-admin
          podAnnotations:
            "istio.io/dataplane-mode": "ambient"
      ingress:
        enabled: true
        className: nginx
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-prod
          nginx.ingress.kubernetes.io/proxy-body-size: "0"
        hosts:
          - host: code.lajas.tech
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - code.lajas.tech
            secretName: forgejo-tls-certificate
    valkey-cluster:
      enabled: false
    valkey:
      enabled: false
    postgresql:
      enabled: false
    postgresql-ha:
      enabled: false
