apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: micropaas
spec:
  destination:
    name: in-cluster
    namespace: micropaas
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
  source:
    repoURL: https://bjw-s-labs.github.io/helm-charts
    chart: app-template
    targetRevision: 3.7.3
    helm:
      valuesObject:
        defaultPodOptions:
          labels:
            "istio.io/dataplane-mode": "ambient"
        controllers:
          main:
            containers:
              main:
                image:
                  repository: docker.io/llajas/micropaas
                  tag: cd54ce6f0b2aeea079ece1ae01ac8291927708c1
                env:
                  DOCKER_HOST: tcp://127.0.0.1:2375
                  SOFT_SERVE_INITIAL_ADMIN_KEYS: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIN5ue4np7cF34f6dwqH1262fPjkowHQ8irfjVC156PCG
                  REGISTRY_HOST: docker.io/llajas
                  GITOPS_REPO: cloudlab
                  GIT_USER_NAME: Khue's Bot
                  GIT_USER_EMAIL: mail@lajas.tech
                  ARGOCD_WEBHOOK_ENDPOINT: http://argocd-server.argocd.svc.cluster.local/api/webhook
              docker:
                image:
                  repository: docker.io/library/docker
                  tag: 27-dind
                command:
                  - dockerd
                  - --host=tcp://127.0.0.1:2375
                securityContext:
                  privileged: true
              nginx:
                image:
                  repository: docker.io/library/nginx
                  tag: latest
        service:
          main:
            controller: main
            ports:
              ssh:
                port: 2222
                protocol: TCP
              http:
                port: 8080
                protocol: TCP
              web:
                port: 80
                protocol: HTTP
        ingress:
          main:
            enabled: true
            className: nginx
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt-prod
            hosts:
              - host: micropaas.lajas.tech
                paths:
                  - path: /
                    pathType: Prefix
                    service:
                      identifier: main
                      port: 80
            tls:
              - hosts:
                  - micropaas.lajas.tech
                secretName: micropaas-tls-certificate
        persistence:
          data:
            accessMode: ReadWriteOnce
            size: 10Gi
            advancedMounts:
              main:
                main:
                  - path: /var/lib/micropaas/repos
                    subPath: repos
                  - path: /var/lib/micropaas/db
                    subPath: db
                  - path: /var/lib/micropaas/ssh
                    subPath: ssh
                  - path: /var/lib/micropaas/web
                    subPath: web
                  - path: /root/.docker
                    subPath: docker-config
                nginx:
                  - path: /usr/share/nginx/html
                    subPath: web
          cache:
            accessMode: ReadWriteOnce
            size: 100Gi
            advancedMounts:
              main:
                main:
                  - path: /var/cache/micropaas
                    subPath: micropaas
