apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: radicle
spec:
  destination:
    name: in-cluster
    namespace: radicle
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
  source:
    repoURL: https://bjw-s-labs.github.io/helm-charts
    chart: app-template
    targetRevision: 3.7.3
    helm:
      valuesObject:
        controllers:
          server:
            type: statefulset
            initContainers:
              setup:
                image:
                  repository: docker.io/llajas/radicle-server
                  tag: latest
                env:
                  RAD_HOME: /var/lib/radicle
                  RAD_PASSPHRASE: ""
                command:
                  - sh
                  - -c
                  - |
                    rad auth --alias=radicle.cloudlab.lajas.tech
                    rad seed rad:zGtLfDcgmBqBUya1qTpzRzpBpoHx
                    rad seed rad:z38YiLVx2e4JC5Xo2qMNDGoMPHE7U
                    rad seed rad:z3pkjF1uaT1cZBrB8tBcCDtXGnrLQ
                    rad seed rad:zdhXFweZXNiVmb6YPV9SFeA5xeZC
                    rad seed rad:z3KcHMAjkkxzys1QyXYgFa4Rfik4D
                    rad seed rad:z3Leck2yN7a8R2NpYtikkmAB8vA22
                    rad seed rad:zLcEuZQwY8hRDUiaSNz8eNRgEpkc
            containers:
              node:
                image:
                  repository: docker.io/llajas/radicle-server
                  tag: latest
                env:
                  RAD_HOME: /var/lib/radicle
                command:
                  - radicle-node
              api:
                image:
                  repository: docker.io/llajas/radicle-server
                  tag: latest
                env:
                  RAD_HOME: /var/lib/radicle
                command:
                  - radicle-httpd
                  - --alias
                  - blog
                  - rad:zGtLfDcgmBqBUya1qTpzRzpBpoHx
                  - --alias
                  - dotfiles
                  - rad:z38YiLVx2e4JC5Xo2qMNDGoMPHE7U
                  - --alias
                  - homelab
                  - rad:z3pkjF1uaT1cZBrB8tBcCDtXGnrLQ
                  - --alias
                  - micropaas
                  - rad:zdhXFweZXNiVmb6YPV9SFeA5xeZC
                  - --alias
                  - nixos-setup
                  - rad:z3KcHMAjkkxzys1QyXYgFa4Rfik4D
                  - --alias
                  - webhook-transformer
                  - rad:z3Leck2yN7a8R2NpYtikkmAB8vA22
                  - --alias
                  - cloudlab
                  - rad:zLcEuZQwY8hRDUiaSNz8eNRgEpkc
          explorer:
            containers:
              main:
                image:
                  repository: docker.io/llajas/radicle-explorer
                  tag: latest
        service:
          server:
            controller: server
            ports:
              radicle:
                port: 8776
                protocol: TCP
              http:
                port: 8080
                protocol: HTTP
          explorer:
            controller: explorer
            ports:
              http:
                port: 80
                protocol: HTTP
        ingress:
          main:
            enabled: true
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt-prod
            hosts:
              - host: radicle.cloudlab.lajas.tech
                paths:
                  - path: /
                    pathType: Prefix
                    service:
                      identifier: server
                      port: 8080
              - host: code.lajas.tech
                paths:
                  - path: /
                    pathType: Prefix
                    service:
                      identifier: explorer
                      port: 80
            tls:
              - hosts:
                  - radicle.cloudlab.lajas.tech
                  - code.lajas.tech
                secretName: radicle-tls-certificate
        persistence:
          data:
            accessMode: ReadWriteOnce
            size: 10Gi
            advancedMounts:
              server:
                auth:
                  - path: /var/lib/radicle
                node:
                  - path: /var/lib/radicle
                api:
                  - path: /var/lib/radicle
