defaultPodOptions:
  labels:
    istio.io/dataplane-mode: ambient
controllers:
  main:
    type: statefulset
    containers:
      main:
        image:
          repository: ghcr.io/silverbulletmd/silverbullet
          tag: v2
        envFrom:
          - secret: silverbullet
service:
  main:
    controller: main
    ports:
      http:
        port: 3000
        protocol: HTTP
ingress:
  main:
    enabled: true
    className: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
      - host: notes.cloudlab.lajas.tech
        paths:
          - path: /
            pathType: Prefix
            service:
              identifier: main
              port: 3000
    tls:
      - hosts:
          - notes.cloudlab.lajas.tech
        secretName: notes-tls-certificate
persistence:
  data:
    accessMode: ReadWriteOnce
    size: 1Gi
    globalMounts:
      - path: /space
