apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps
spec:
  goTemplate: true
  goTemplateOptions:
    - missingkey=error
  generators:
    - list:
        elements:
          - namespace: test
            app: example
          - namespace: llajas
            app: blog
          - namespace: llajas
            app: notes
          - namespace: llajas
            app: homelab-docs
          - namespace: finance
            app: actualbudget
  template:
    metadata:
      name: '{{.namespace}}-{{.app}}'
    spec:
      project: default # TODO
      destination:
        name: in-cluster
        namespace: '{{.namespace}}'
      source:
        repoURL: 'oci://registry.127.0.0.1.sslip.io/{{.namespace}}/{{.app}}'
        targetRevision: local
        path: '.'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
          - ServerSideApply=true
